name: Publish on GitHub registry
on:
  push:
    branches: [main]
    tags: ['**']
  pull_request:
    types: [opened, synchronize]
jobs:
  test:
    name: Test with Jest
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node.js v14
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Install NPM depedencies
        run: npm install
      - name: Run Jest
        run: npm run test
  format:
    name: Check format with Prettier
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node.js v14
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Install NPM depedencies
        run: npm install
      - name: Run Prettier
        run: npm run format:check
  publish:
    name: Publish to GitHub registry
    needs: [test,format]
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Ensure tag validity
        run: |
          if [ $(jq -r .version package.json) != ${GITHUB_REF/refs\/tags\//} ]; then
            echo "Error: $GITHUB_REF does not match package.json version"
            exit 1
          fi
      - name: Setup Node.js v14
        uses: actions/setup-node@v2
        with:
          node-version: '14'
          registry-url: 'https://npm.pkg.github.com'
      - name: Publish the package to GitHub registry
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
